//@version=6
// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © chazwoza

strategy("Charles EMA 20-50 cross strategy")

ema20 = ta.ema(close, 20)
sma20 = ta.sma(close, 20)
ema50 = ta.ema(close, 50)
sma50 = ta.sma(close, 50)

long = sma20 > sma50
short = sma20 < sma50

lotsize = 1000 // how much to trade

if long
    strategy.close("Short")
    strategy.entry("Long", strategy.long, lotsize)
if short
    strategy.close("Long")
    strategy.entry("Short", strategy.short, lotsize)
   
